### ISSUE TITLE
Package Citation?

### ISSUE THREAD

**Issue by samuel-marsh** [Oshlack/speckle#1]
Hi,

First, thanks for creating such a simple, yet really helpful package (with a great vignette!).  I would like to cite the package in manuscript I'm preparing.  Could you please let me know other than package name/GitHub url, whether there is other information or preprint/manuscript I should include when citing the package?

Thanks again!
Sam

**Comment by bphipson** [comment]
Hi Sam,

Thank you for using speckle and I'm glad you found it useful! I'm in the processing of writing an accompanying paper for the software but unfortunately no preprint just yet. I can let you know when the preprint goes up.

Cheers,
Belinda

**Comment by samuel-marsh** [comment]
Hi Belinda,

Excellent, thanks so much!

Best,
Sam
