### ISSUE TITLE
Compositional effects

### ISSUE THREAD

**Issue by GBeattie** [Oshlack/speckle#2]
Hey, great package!

I was wondering if there's any analog included in this package (can't see one in the documentation, but I often miss things..) or would you consider including an analog to the compositional correction carried out by packages such as scCODA? Maybe the simple answer is to recalculate proportions using scCODA and use speckle for the stats.

Either way, combining your statistical approach with something that corrects for compositional effects would be very powerful!

Thanks,
Gordon

**Comment by bphipson** [comment]
Hi Gordon

Thanks for using my package! At this time, there is no analog for
compositional correction that you mention above. I will look into this,
thank you for the suggestion.

Cheers,
Belinda
