### ISSUE TITLE
Two-Way ANOVA?

### ISSUE THREAD

**Issue by DennisFeige** [Oshlack/speckle#5]
Hello,

I have an experimental design where I treat cells with a control substance or my drug and take cells after different time points.
Eg. Ctrl+2h, Ctrl+4h... and Drug+2h, Drug+4h...
`propeller()` performs an ANOVA but I would like to do a two-way ANOVA to test for significance of drug, timepoint and drug+timepoint. Afterwards I would like to do a post-hoc test. Is that possible with your package or do you maybe have a different suggestion for statistical analysis for this kind of experimental design?

Best and thanks for any help,
Dennis

**Comment by bphipson** [comment]
Hi Dennis

Thanks for your interest in propeller. You can fit a multivariate linear model on the transformed proportions. Do you want to test the interaction between drug and timepoint? I wasn't sure what you meant by drug+timepoint. How many time points do you have? I take it there are two levels for drug - "control" and "drug". In the vignette there are examples of fitting multiple covariates including an ANOVA example with two covariates and then performing t-tests following the ANOVA. This is done with the propeller.anova() and propeller.ttest() functions. The workflow is a bit different for these more complex experiments, but the vignette has a good level of detail for how to fit different kinds of models using propeller.

Hope that helps.

Cheers,
Belinda
